version: '3'

services:
  nginx:
    image: nginx:1.18.0-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites/app1.conf:/etc/nginx/sites-enabled/app1.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app1

  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    command: bash -c "APP_ENV=development bundle exec ruby myapp.rb -p 3000 -o 0.0.0.0"
    volumes:
      - ./app1:/myapp
