version: '3'

services:
  nginx:
    image: nginx:1.18.0-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites:/etc/nginx/sites-enabled
      - ./lp:/var/www/lp
    ports:
      - "80:80"
    depends_on:
      - auth
      - org
      - app1

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    command: bash -c "APP_ENV=development bundle exec ruby myapp.rb -p 3000 -o 0.0.0.0"
    volumes:
      - ./auth:/myapp

  org:
    build:
      context: ./org
      dockerfile: Dockerfile
    command: bash -c "APP_ENV=development bundle exec ruby myapp.rb -p 3000 -o 0.0.0.0"
    volumes:
      - ./org:/myapp

  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    command: bash -c "APP_ENV=development bundle exec ruby myapp.rb -p 3000 -o 0.0.0.0"
    volumes:
      - ./app1:/myapp
