version: '3'

services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    command: bash -c "APP_ENV=development bundle exec ruby myapp.rb -p 3000 -o 0.0.0.0"
    ports:
      - "3001:3000"
    volumes:
      - ./app1:/myapp
